### ISSUE TITLE
Adding Reviewers To This Project

### ISSUE THREAD

**Issue by mikeln** [bloomberg/powerfulseal#102]
Is there a procedure for adding reviewers or requesting to be added as a reviewer/owener to this project?

**Comment by seeker89** [comment]
@kpfleming will be able to advise. Would you be interested to join as a maintainer ?

**Comment by mikeln** [comment]
As of now, yes.  However, I do not know how long my company will be willing to give me the time to fully fill that position.

**Comment by kpfleming** [comment]
At this time our company policy is that only Bloomberg staff members are permitted to have 'write' access to repositories in our organizations. Since GitHub uses that permission as a trigger for accepting reviews from official reviewers, there's no mechanism for us to provide that ability to you (we would, if there was a way to do it which didn't also grant 'write' permission).
