### ISSUE TITLE
Retire the demo mode (Heapster is now deleted)

### ISSUE THREAD

**Issue by seeker89** [bloomberg/powerfulseal#109]
[Heapster](https://github.com/kubernetes-retired/heapster) has now reached EOL with Kubernetes 1.13. We should remove the mode that relies on it.

**Comment by dgzlopes** [comment]
Hello! I think we can keep the mode working with little change after reading our `heapster_client.py`. 

Seems like the 'new' default metric collection approach and alternative to Heapster is the Kubernetes metrics-server [[0](https://github.com/kubernetes-incubator/metrics-server)] that is starting to be used by many other k8s projects (actually `kubectl top` is using this [[1](https://kubernetes.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/)]). I said little change because both implement the same Resource Metrics API (metrics.k8s.io API)  [[2](https://github.com/kubernetes/metrics)]. 

If you think it's a good idea I can put some more work on this, check if the new `/apis/metrics.k8s.io/v1beta1/pods` is fully compatible and if not try to implement the new changes! :yum:

[[0](https://github.com/kubernetes-incubator/metrics-server)] https://github.com/kubernetes-incubator/metrics-server
[[1](https://kubernetes.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/)] https://kubernetes.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/
[[2](https://github.com/kubernetes/metrics)] https://github.com/kubernetes/metrics

**Comment by seeker89** [comment]
Brilliant - thanks for looking into that @dgzlopes !

**Comment by dgzlopes** [comment]
Took a closer look on this one and happy to say that no huge breaking changes here . Overall the response structure is the same, but we should make some small fixes to keep the mode working correctly:

 - Fix CPU parse. Metrics-server uses core-nanoseconds (summaryMetricsSource [[0](https://github.com/kubernetes-incubator/metrics-server/blob/2d9f2bba8a59e2900f03fa3a105596e31acd1ea9/pkg/sources/summary/summary.go)] takes data from Kubelet that returns nanoseconds [[1](https://github.com/kubernetes-incubator/metrics-server/blob/0e3264e1a63651d251d748421ebc138ead3fef14/vendor/k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1/types.go#L173)]) as the CPU unit instead of milicores.
- New POD_METRICS_PATH is `/apis/metrics.k8s.io/v1beta1/pods` instead of `/apis/metrics/v1alpha1/pods`.
- Fix `test_heapster_client.py`. Both the mock response and the `test_parse_cpu_string()`.
- Change all the project references from Heapster to Metrics-server. From docs to code.

[[0](https://github.com/kubernetes-incubator/metrics-server/blob/2d9f2bba8a59e2900f03fa3a105596e31acd1ea9/pkg/sources/summary/summary.go)] https://github.com/kubernetes-incubator/metrics-server/blob/2d9f2bba8a59e2900f03fa3a105596e31acd1ea9/pkg/sources/summary/summary.go
[[1](https://github.com/kubernetes-incubator/metrics-server/blob/0e3264e1a63651d251d748421ebc138ead3fef14/vendor/k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1/types.go#L173)] https://github.com/kubernetes-incubator/metrics-server/blob/0e3264e1a63651d251d748421ebc138ead3fef14/vendor/k8s.io/kubernetes/pkg/kubelet/apis/stats/v1alpha1/types.go#L173
