### ISSUE TITLE
Powerfulseal only restarting the pods instead of killing

### ISSUE THREAD

**Issue by rkharat** [bloomberg/powerfulseal#143]
**Powerfulseal only restarting the pods instead of killing**
I am able to start powerfulseal tool successfully .
I have observed that it only restarting the pods instead of killing as name of the pods not changing. Also the Age of pods does not change.

Can you confirm if this is expected behaviour.

**To Reproduce**
1. run on kubernetes cluster with autonomous mode

**Expected behavior**
Pod should be killed instead of restarting

**Screenshots**
attached screen
**Environment (please complete the following information):**
 - Operating System and Version: [e.g. Ubuntu Linux 16.04]
![powerfulseal1](https://user-images.githubusercontent.com/23660170/63683073-0da17980-c817-11e9-902a-f1ea0102503c.png)

**Comment by dgzlopes** [comment]
I would say it's the expected behavior.

 Pods are killed forcefully by Powerfulseal on Kubernetes to simulate a container failure. So when Kubernetes detects that a pod has crashed,  the [restartPolicy ](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy) restarts the pod and the restart count is increased.

**Comment by rkharat** [comment]
> can

It is ok to restart but my concern is why the pod names not changes? and also the Age of pod?

**Comment by seeker89** [comment]
Hi @rkharat 

When your pod dies in `kubernetes`, it is restarted, but its name or age don't change.
`PowerfulSeal` purposefully crashes the pod (the process inside of the container), so that `kubernetes` has to kick in and do its thing. 

Try for yourself - if you `kubectl exec` into one of your containers, and kill the process inside, the age or the name of the pod will not change, it will be restarted.

**Comment by rkharat** [comment]
Ok, so here is my understanding(correct me if I am wrong) powefulseal kills the process inside the pod  so that k8s could automatically restarts the pod.
And it does not work like kubectl delete.

**Comment by seeker89** [comment]
That's correct. When saying `kubectl delete pod`, you are not simulating a crash of your process. You are telling `kubernetes` to delete that, and potentially create another one, if there is a `deployment` or a `replicaSet` that managed the given pod. There is a few things happening (`gracePeriod`, etc), but the bottom line is that you are not simulating a life-like situation with `kubectl delete pod`.

That's why `PowerfulSeal` crashes/kills the process itself.

**Comment by rkharat** [comment]
Thank you so much @seeker89 and @dgzlopes for quick help.
I am closing the issue as I got the clarification of my doubts.

**Comment by seeker89** [comment]
Happy to help 👍
