### ISSUE TITLE
Label mode uses invalid characters for specifying days

### ISSUE THREAD

**Issue by benceszikora** [bloomberg/powerfulseal#213]
I Label mode, the way to define what days a pod can be killed is by using a comma separated list:
```
mon,tue,wed,thu,fri
```
https://github.com/bloomberg/powerfulseal/blob/master/LABELS.md

Commas however are not allowed by the Kubernetes spec in label values:
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
```
Valid label values must be 63 characters or less and must be empty or begin and end with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between.
```

Would is make sense to change the separator, or add support for an additional one, maybe `-`, `_` or `.`?

Currently trying to set the label as specified in the example will simply fail.

**Comment by seeker89** [comment]
Great catch. I think that the cleanest would probably be to use dashes instead. What do you reckon @benceszikora ?

**Comment by benceszikora** [comment]
The easy fix would be to switch to dashes, I agree. In an ideal world however, all of these would be annotations I think. The character set allowed there is much more forgiving.
That's a much bigger change though looking at the code, so not sure what your thoughts are on that?

**Comment by seeker89** [comment]
Actually, supporting annotations would be pretty straightforward. It would require:

1. Adding a new field in the pod class in https://github.com/bloomberg/powerfulseal/blob/f5b9364fd66482f9d003223dafbc4ebadef66a1c/powerfulseal/k8s/pod.py#L24-L36

2. Populating that field when reading from kubernetes in https://github.com/bloomberg/powerfulseal/blob/f5b9364fd66482f9d003223dafbc4ebadef66a1c/powerfulseal/k8s/k8s_inventory.py#L105-L117

3. Change the 6 occurrences of direct access to `pod.labels` like this one https://github.com/bloomberg/powerfulseal/blob/f5b9364fd66482f9d003223dafbc4ebadef66a1c/powerfulseal/policy/label_runner.py#L122 to use a new method instead, which looks into either labels (for backwards compatibility) or annotations.

Also, step 1) and 2) are actually optional, because the annotations will already be accessible in `pod.meta.metadata.annotations`, but they would make the code cleaner.

**Comment by benceszikora** [comment]
@seeker89 I created #217 for this, let me know what you think!
